export const listPresentFilter = [
    {
        id: '1',
        title: 'Tiến Lên',
        name: 'Tiến Lên',
        label: '6789',
        catId: '81',
        link: '/sim-tien-len',
        showCat: ['/sim-tien-3', '/sim-tien-4', '/sim-tien-5'],
    },
    {
        id: '2',
        title: 'Tam Hoa',
        name: 'Tam Hoa',
        label: 'Sim Tam Hoa',
        catId: '80',
        link: '/sim-tam-hoa',
        showCat: [],
    },
    {
        id: '3',
        label: '4444',
        title: 'Tứ Quý',
        name: 'Tứ Quý',
        catId: '68',
        link: '/sim-tu-quy',
        showCat: [],
        notFilterItem: ['category'],
    },
    {
        id: '4',
        title: 'Lặp Kép',
        name: 'Lặp Kép',
        label: 'AA.BB',
        catId: '67',
        link: '/sim-lap-kep',
        showCat: [
            '/sim-lap',
            '/sim-kep',
            '/sim-kep-2',
            '/sim-kep-3',
            '/sim-kep-4',
            '/sim-lap-2',
            '/sim-lap-3',
            '/sim-lap-4',
        ],
    },
    {
        id: '5',
        title: 'Thần Tài',
        name: 'Thần Tài',
        label: 'Thần Tài',
        catId: '72',
        link: '/sim-than-tai',
        showCat: [],
        notFilterItem: ['category'],
    },
    {
        id: '6',
        title: 'Ông Địa',
        name: 'Ông Địa',
        label: 'Ông Địa',
        catId: '70',
        link: '/sim-ong-dia',
        showCat: [],
        notFilterItem: ['category'],
    },
    {
        id: '7',
        label: 'taxi/hotline',
        title: 'Taxi/hotline',
        name: 'Taxi/hotline',
        catId: '74',
        link: '/sim-taxi',
        showCat: ['/sim-taxi-2', '/sim-taxi-3', '/sim-taxi-4'],
    },
];
